name: indy-plenum-build
on: [ push, pull_request ]

jobs:

  indy_plenum_tests:
    name: Indy Plenum Test Slices
    runs-on: ubuntu-18.04
    #TODO: move this to hyperledger?
    container: wwjbarnes/indy-plenum-ci:latest
    strategy:
      matrix:
        module: [plenum]
        slice: [1, 2, 3]
      fail-fast: false
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: pip install .[tests]

      - name: Run Indy Plenum ${{ matrix.module }} test slice ${{ matrix.slice }}/3
        run: RUSTPYTHONASYNCIODEBUG=0 python runner.py --pytest "python -m pytest -l -vv --junitxml=test-result-plenum-${{ matrix.module }}-${{ matrix.slice }}.xml" --dir "${{ matrix.module }}" --output "test-result-plenum-${{ matrix.slice }}.txt" --test-only-slice "${{ matrix.slice }}/3"

      - name: Publish Test Report
        uses: scacap/action-surefire-report@v1
        with:
          check_name: Indy Plenum ${{ matrix.module }} Test Report for slice ${{ matrix.slice }}/3
          github_token: ${{ secrets.GITHUB_TOKEN }}
          report_paths: test-result-plenum-${{ matrix.module }}-${{ matrix.slice }}.xml

  indy_plenum:
    name: Indy Plenum Tests
    runs-on: ubuntu-18.04
    #TODO: move this to hyperledger?
    container: wwjbarnes/indy-plenum-ci:latest
    strategy:
      matrix:
        module: [common, crypto, ledger, state, storage, stp_core, stp_zmq]
      fail-fast: false
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: pip install .[tests]

      - name: Run Indy Plenum ${{ matrix.module }} tests
        run: python -m pytest -l -vv --junitxml=test-result-plenum-${{ matrix.module }}.xml ${{ matrix.module }}

      - name: Publish Test Report
        uses: scacap/action-surefire-report@v1
        with:
          check_name: Indy Plenum ${{ matrix.module }} Test Report
          github_token: ${{ secrets.GITHUB_TOKEN }}
          report_paths: test-result-plenum-${{ matrix.module }}.xml

  lint:
    name: Lint
    runs-on: ubuntu-18.04
    #TODO: move this to hyperledger?
    container: m00sey/indy-node-lint:latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: flake8
        run: python3 -m flake8
